language: node_js
node_js:
- 8.4.0
sudo: required
cache:
  directories:
  - node_modules
before_install:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- npm i -D uglifyjs-webpack-plugin
install:
- npm install
- npm run ng-deploy
- ls -l
script:
- docker build -t $DOCKER_USERNAME/se234-lab10-client .
- docker push $DOCKER_USERNAME/se234-lab10-client
service: docker
env:
  global:
  - secure: vZmXGDWvkp6CIVWxzKvbLATWdpgcOYmJ5Whv5YCeX1Ycy+Brfxmmq4/3k3n02jg+zjsltKSZj2NEaZaWYu0Ih8cI+B1VnV9dDWPMqbU8Ll2yfIqXOrfOapLzh1jk97u/NwY0KH8cCw3cM27fUZcExHuyFNZ/BcIud13+Ow68eVz0gYyj0mrxwF8nMQBeRamcK/is+whuFEQ3dWuKF3ftNvYaU4Hw2uU7uUENlGokaTL13xFSFY+aSZcOTMwnEc+nGxjjRpLJBp3pTnUzTPyalo+yByEo1WFuMpTBh2bfyH6/A+keXX4YJjdak1yTyXVGEtGfkdHy7afsJOvkB0dA9T9yJTWruhbv2Ee42qTpc+Bp9dq0DtMZBCnOIz8A94T1bXa+xjeTtSWT3bREpIFyfyemH20DPBRA3RWG6192JoQjIjwzAM5ALR3fNsIcPXXhfKSnykcv0u94QxoZjcM09iVJltqtAp/ajSXmO3YuVed4mb6sYFnd3+tH4eDPALs5hv8Fa/l0DLLhH5Eqk60+Sl6tLOutxRrmmH2UvE3EcU7vb0xY4BgvNGFxOXlV95s8q8MZ2iq6c+oIPd25sg19hstwOKfuoV2L63wa848+f0YvANlYIbEghqqWeoeLifTcV31xouv6bSqKSh9HY/b/hYJRfyYm25B5N5kec6pjcuo=
  - secure: SCIRT0+VMScEpGhX8X4hoGnqVlxkWeII9Sz0w1zdDX25+wPCgQSouP/Q3SAylk/IEz8TRX2fP4DlXorI5GFAgnxizfyp0dVcPbKctFozNxLtaH125XYj+uLSoFxtNel23ClDAoOIGeX+cPKip1+YVjbTvCyMX7UGD7L6PaIhFMkWj7/fAbFT1CHWVf4Xm7LbPgnJOVd5VUeCLEWNdou7SrR5p5NwnDAFS6KIOJMkU9PcUyqoCNLHoOiLcU3uqoETfRn4boUcD6otrEJqscn9uIYshTJ8ZIBOIO8JttfyHGrzFE1JeLwSckiig3+vV5L4cS8CIt7I2KNZT62Ory/0N4NTqwtBE4A9rbUdsqvf66bdMWrPu00Ew6XlZnjLssgBwksWCDwOlqqLK4AfV7eKCf9uoBQwaQKjICQ7bmIaiE8YiKt4t3+myG3n4bI5LDQ8v89EAiwz2GNmSbqZQHHxb6vExRELU19CEkku2IleXtpCoRSaC3nm3wPCEcIkXUgNFCn/og0FE5uDdzUPtRrV95/ZURA74nbaxgfnOXjhr7AoTN3UvGXgczUtvQl+KTalcgbJyY73LQpWncAWqUU/oEtxoxW534Zyil4X6OIaTv0riTYUOHA30p3XBfQ+O/SkE19SDRt/33im5YbyFVrHkC2K3PPZiDOYNS6Nz52taeQ=
  - secure: MEuePVq3G7ndBrzxlsFObZZMPGUJutXFYJ8pAFpLXbcMqA89u657kVo/yfA+CxJzvk1w2XQ0C7snPqfs+WWVFykyRPwHGZBaQY7/MVexo+Ccol9uIELo7DA3FfKMwH3TVu0NB+CjPZY5Hw0jUgATcJ5LxaqV/FtCagk7mZ2oShyMyFmCJoscrijhADdKLlbIfmDq/D+1OUlPCb65FjBXeYjtAKQgERZlYDWbsRFbMyk0RIz2wFKzD9YGEAJ38Pxzp92lKEEyUwPcACK29dpTQRqvqKqy3N90kXTbdz9gKbHhoKQxvfeqI5Nq1Fon2H16boFNytE4uXdwDoDxqBzdH/DEsgevyEt/ImrglUt79SAbsKOik8UPXU4B4tBhheHZp/4qDIhBMzZIXGM2bVz1xiHYsQ0ZOZTSlQi9kGf3I0JMBZ1X+VA9TPgcVfYJx6rFSj7yv0MeA4D4e5OqxrhGQRy8wP1yq4iUzL0b1ev2kqp09CZRMYpxcRzJujzixmBecxvgT6UfDytD8H7jF+T0+rXXwJ/8BO0OWyDJcoN19xsAv6Q7nOj2fLZbUJZeeLBQnAtvNAgOrXaKzSuPj/tyuzSmbdw5zIf2Vm4Azq0Sj/V41/TPjmXTGu1b3hVp3VUi65lGNzC4uu6ynSLYCHWwaOxWcbrPQt5CDAi9pIcBE/Y=
