language: java
before_install:
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/1.20.1/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- docker login -u "592115022" -p "$DOCKER_PASSWORD"
install:
- mvn install -Dmaven.javadoc.skip=true -B -V
- ls -l
- docker build --build-arg JAR_FILE=/target/backend.jar -t 592115022/se234-lab10-backend .
- docker push 592115022/se234-lab10-backend
- docker pull 592115022/se234-lab10-client
script:
- docker-compose -H "$DOCKER_HOST" up -d
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - secure: aBV5lWZ9i74GOKgFPqnixjiCPAJlVw4rdMQIPz3kmyvsFlc1TNb/wQX/eFYXVii4HoVlVOu5bhXbCCcl0Rdb2sAUOhijW6JRfi4gMhVOfhltlFm/OOcNBCXyCObJ6xsLMpC4mWp0JMjxOGGoDV4WU3tLqulfm1H+4ZxF16ihsimnOohKZ+sPZGh2Npv8DXxyQLjzQ8EpIX6YyRPHoNdcqN85Ngjwlg7TdM+T2ST2qYNsHfQWaXsfkPhupwiAFPOUXxtZ0hS0wUUblnwJTl0yRekdZ9HrQie/SxWdtEOOQRytMefVbBD7ESIZd/60muFhkg66X4d5QZZPmmg83PbjQphjal6SVZM8F1L4benHOtARIxRAQTPtlg0o20Wickro2jNJSRthZyvJIDkbVkAc9GBHLPVqUKeg58uf82F0i3M1VgM4wEJX2PXg7r1sY5Uev7j03ptb032gpmQbLSD7kREAO48IsC5yVBEgTpM+P7ON6BYDo18VVdvBZJz129hq5SCDZ57d1Hq7Vb4qUESP783Rs+QiWJ4azuuUqNmjcCVGZ/3c6zWoyI6TtKAir5gHvIyNOXWC60bQdmsrqX14sOEDS6fszG8zz8Pbo8Ca/zqkS2yjHrPce8fJYJRScsndAfpzMBknwoTSAyUj3X94mi9EsGEpONBTgEQa7KzMELc=
  - secure: Uo0BBE/ITLAFHsmqZfTaiVy8yLIFqe3313ZFZUlsiweUBw5TMRuCUdf4GaUsXTNi8CL94mJlVuZGgqtiTmC/Nf9Nd6uyRZrC5C+PmQHP7QD62wGdCzSj4+3y2VUii3+aKIMBeGVa9eZssTp8jnucsVONAya2Rok+SstQnDNNE6UVfoTNaZKGWyTRqq/sxS9QrB/e2aNyClnHxryAp6wq5Upn8wRTe095g/JRK/9xEmZfTUTqeDjCp+5nAyaTKNsH2lD/BDBQrlvsoeP2AF+NfGiVgdfPK6TfXuRChRO/BSxmcAKDocCThHNywvYTQ6Zm5W0sjeW/vXku1rY96i/Q/aX15DjDJ31GffIEuYgyLcp3oAxjcH/udmKWF/JRmOMWASokw3nQvf5uBpEJdm2BnBTStZDEx3dAmAqhOUiLkhN/p1BJ6ek375ZpArM8YZ+haDBQExFYUr49+m553xTU5cg3vEwdKO02qR6YY/lrpESNWs4t2JV6PB0xU/GXKdOC2hUiwNmqQ3GfkFe9Xk2Je0YDVF87Mm/6tic8chauOntguRtC/0L+wQVUsAxIjaSLsm3K1eysM8Sl9fyDpme9DNZqvd7IW5NboyeCormrXAytMfgVbMEXh1otB/Thr+NicSNdBpsxCmG0wQ+WBofcBPyj5R9Xo9DVvxiqP7VOL+A=
  - secure: RJuxR81RIeZy74JSuTBJDXJbKP1NkZbYhfEzyt2swluRoK4McLgjEU4ZfJYsr/baIH0hxm3/NyLCl1XZaCRHx4AnZAk7l51NhDYza/g7jTV1Ud0ArxuOhrsNt8C9KVsoufk0mbgxX7B5CAubTxQFOXsNbyAXqIOnRJZCGgm/I776x/Yl8SAzE7fX79aP//Fy8fJe05iHY8PqtX5Bqe1w7vVLbHizrnSqepfaNiU7c0LsUpVaNl350RSl+EnFGkqY2uAgw7yIt4xy24MPYbUY2Cq2FNYSHsQKLkiHv6YV7uRlujbKum1rV0bjuh+xjHxGdVOH3H3dBpV9d7xTOuLVXG9FdJAHJL0uHZLUV9G9LY6269RRC+YcEbz9LkndnKLPbDILyHjrsnQkT2+T9gUfzHchu5Tp1WJbC7QU/4xg9SjaDylOSgDYFUG+dOnB6vYHWiPTyP3RhR3/WWxp7qFhteU2JnxddJkmf4snmmgWDalJ3I8JBd17T+mLnGvVpGNDn1C8Aubzk+jQ2xZiLuvtl1+Y8FIFKEtA6LT+FywjXoU65XqscT0Avhv7rXQHfDk3/9Id1tcSaPOdGj8T0tjtQDGvRMbWpZp7umbq3Jom0bnR5PLUODcKUZDAPUU135Y2B4e+ZHPF1w6tdvz7HrDsGi6dAJytCS62X7KAV8PVBYQ=
